version: "3.4"
services:
  mysql:
    build: rdb/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=unity
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=ca21engineer
      - MYSQL_PASSWORD=pass

  redis:
    restart: always
    image: redis:3.2.4-alpine

  api-server:
    restart: always
    build: apiServer/target/docker/stage
    ports:
      - 18080:18080
      - 18081:18081
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  reverse-proxy-server:
    restart: always
    build: reverseProxyServer
    ports:
      - 8080:8080
